# Generated by Django 2.2.1 on 2019-06-27 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfoform',
            old_name='prifile_pic',
            new_name='profile_pic',
        ),
    ]
